### ISSUE TITLE
Vignette

### ISSUE THREAD

**Issue by ybkamaleri** [statisticsnorway/klassR#7]
Any plan to create a vignette for this package or how it can be used?

**Comment by sjentoft** [comment]
Thanks for the feedback and good idea! I will try to work on this. In the mean time we have a short tutorial here showing some of the main uses: https://statisticsnorway.shinyapps.io/KlassR_tutorial/

**Comment by sjentoft** [comment]
A vignette is now included in version 0.1.10 and can also be viewed here: https://statisticsnorway.github.io/klassR/articles/klassR-vignette.html
